### ISSUE TITLE
Component names in templates

### ISSUE THREAD

**Issue by klumba12** [qgrid/ng#4]
what we're going to use in templates for defined rows and columns, waiting your comments bellow
My variants
```html
<q-grid:(tr|td)>
```
```html
<q-grid:(row|column)
```

**Comment by vkorolev** [comment]
I like tr|td more, because it's shorter, clearer and this naming is common for HTML. The only possible problem is synchronization with scope's variables: `$row` and `$column`. Probably it might be the point of confusion.

**Comment by titovmx** [comment]
I don't like this html native names, but probably it will be clearer and accustomed to use for most users.
@vkorolev, do you mean sync between ```tr```|```td``` and ```$row```|```$column``` for user? Or some technical aspect?

**Comment by vkorolev** [comment]
@titov-max, no technical aspects, only possible naming confusion

**Comment by iamvladdy** [comment]
`tr | td` maybe not so pretty but it's oldschool and more suited to standards. I'd choose it.

**Comment by klumba12** [comment]
I like that it only 2 symbols there and still readable

**Comment by peaceful-djony** [comment]
tr/td - applies to table terms. Also for me row/column- clearer. As for minimalism in naming - we can use row/col (only two additional simbols).
