### ISSUE TITLE
Attribute naming convension

### ISSUE THREAD

**Issue by klumba12** [qgrid/ng#42]
pinned="left" vs pin="left"
isVisible, isDefault vs visible, 'default' (reserved)
moveable, filterable, resizable vs canMove, canFilter, canResize

**Comment by klumba12** [comment]
I'like: pin, isVisible, canMove

**Comment by titovmx** [comment]
What do you think about **_pinTo_**? From suggested variants I like **_pin_** more
**_isVisible_** and **_isDefault_** are good to avoid of confusion
And I prefer **_moveable_**
