### ISSUE TITLE
test json data

### ISSUE THREAD

**Issue by klumba12** [qgrid/ng#5]
Anybody knows where we can find good test cases for the grid?
I found out one that looks amazing:
https://github.com/arangodb/example-datasets/tree/master/RandomUsers

but it's not valid json, are we going to preprocess it?

**Comment by etokareva** [comment]
Maybe, use fake data generator? e.g. https://github.com/Marak/faker.js (or https://www.mockaroo.com/)

**Comment by klumba12** [comment]
Good links, however i've added script that convert data to required format
https://github.com/klumba12/qgrid/blob/3a04e33254b85781c4e208c4c4db6a12b34eeb1f/scripts/tojson.js
