### ISSUE TITLE
Compound keys

### ISSUE THREAD

**Issue by klumba12** [qgrid/ng#7]
Are we going to support format like that:
```json
    {
      "name": {
	"first": "Diedre",
	"last": "Clinton"
      },
      "gender": "female",
      "birthday": "1959-11-06",
      "contact": {
	"address": {
	  "street": "2 Fraser Ave",
	  "zip": "81223",
	  "city": "Cotopaxi",
	  "state":"CO"
	},
	"email": ["diedre.clinton@nosql-matters.org",
		  "clinton@nosql-matters.org",
		  "diedre@nosql-matters.org"],
	"region": "719",
	"phone": ["719-7055896"]
      },
      "likes": ["swimming"],
      "memberSince":"2009-03-14"
    } 
```

Are we going to support compound keys?
e.g.
```javascript
$scope.columns = [{
 key: 'name.first', //  compound path
 title: 'First Name'
}
];
```

**Comment by vkorolev** [comment]
Yes, I think, it's a great option which might be very useful for user

**Comment by vkorolev** [comment]
But probably it would be better to have a function "key"?

```
$scope.columns = [{
  key: function ($row) { return $row.name.first; },
  title: 'First Name'
}, {
  key: 'gender',
  title: 'Gender'
}];
```

**Comment by klumba12** [comment]
Good point, need to think about 'key' semantic if pass the function is ok. Cause the same we can do in template, that can be reflected in the future model...And you wont be able to use a key in template if that is a function
```html
<q-grid:td key="name.first">
{{$row['name']['first']}}
</q-grid:td>
```
In the other hand if wouldn't be able to set that in javascript we'll force to create all templates(view,edit etc.)
